#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : require
layout(set = 0, binding = 0) uniform accelerationStructureEXT g_tlas;
layout(set = 0, binding = 1, std430) buffer Result { uint hit[2]; } result;
void main()
{
    for (uint i = 0; i < 2; ++i)
    {
        rayQueryEXT query;
        rayQueryInitializeEXT(query, g_tlas, gl_RayFlagsOpaqueEXT, 255,
                              vec3(i == 0 ? 0.0 : 4.0, 0.0, 1.0),
                              0.001, vec3(0.0, 0.0, -1.0), 10.0);
        while (rayQueryProceedEXT(query)) {}
        result.hit[i] = rayQueryGetIntersectionTypeEXT(query, true) ==
                        gl_RayQueryCommittedIntersectionTriangleEXT ? 1 : 0;
    }
}
