#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_buffer_reference_uvec2 : require

layout(local_size_x = 64) in;

layout(std430, binding = 0) buffer OffsetBuffer
{
	uint offsets[];
};

layout(buffer_reference, std430, buffer_reference_align = 4) buffer TargetBuffer
{
	uint data[];
};

layout(push_constant) uniform PushConstants
{
	uvec2 base;
	uint count;
	uint value;
} pc;

void main()
{
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= pc.count) return;

	uint offset = offsets[idx];
	uint element = offset >> 2;
	TargetBuffer target = TargetBuffer(pc.base);
	target.data[element] = pc.value;
}
