#version 460

#extension GL_EXT_ray_query : require
#extension GL_EXT_ray_tracing_position_fetch : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0)
uniform accelerationStructureEXT topLevelAS;

layout(set = 0, binding = 1, std430) buffer ResultBuffer
{
	vec4 positions[3];
} result;

void main()
{
	result.positions[0] = vec4(99.0);
	result.positions[1] = vec4(99.0);
	result.positions[2] = vec4(99.0);

	rayQueryEXT query;

	rayQueryInitializeEXT(
		query,
		topLevelAS,
		gl_RayFlagsOpaqueEXT,
		0xff,
		vec3(0.0, 0.0, 1.0),
		0.0,
		vec3(0.0, 0.0, -1.0),
		10.0);

	while (rayQueryProceedEXT(query))
	{
	}

	if (rayQueryGetIntersectionTypeEXT(query, true) ==
	    gl_RayQueryCommittedIntersectionTriangleEXT)
	{
		vec3 fetched[3];

		rayQueryGetIntersectionTriangleVertexPositionsEXT(
			query, true, fetched);

		result.positions[0] = vec4(fetched[0], 1.0);
		result.positions[1] = vec4(fetched[1], 1.0);
		result.positions[2] = vec4(fetched[2], 1.0);
	}
}