#version 460
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_cooperative_matrix : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types : require

struct MatrixData {
    float16_t[256]  float_values;
};

layout(local_size_x=64, local_size_y=1, local_size_z=1) in;

layout(set = 0, binding = 0) readonly buffer InputBuffer
{
    MatrixData in_data;
};

layout(set = 0, binding = 1) buffer OutputBuffer
{
    MatrixData out_data;
};

void main()
{
    coopmat<float16_t ,gl_ScopeSubgroup, 16, 16, gl_MatrixUseAccumulator> float_matrix;

    coopMatLoad(float_matrix,
                in_data.float_values,
                0,
                16,
                gl_CooperativeMatrixLayoutRowMajor);

    coopmat<float16_t ,gl_ScopeSubgroup, 16, 16, gl_MatrixUseAccumulator> float_result = float_matrix + float_matrix;
    float_result = float_result * float_matrix;
    float_result = float_result / float_matrix;
    float_result = float_result - float_matrix;

    coopMatStore(float_result,
                 out_data.float_values,
                 0,
                 16,
                 gl_CooperativeMatrixLayoutRowMajor);

}
